# Amahi HDA platform settings

defaults: &defaults
  dummy_mode: false

development:
  <<: *defaults
  dummy_mode: true

test:
  <<: *defaults

system:
  <<: *defaults
  dummy_mode: true

production:
  <<: *defaults

